# Exercise 2: Lasso

## Plan

1. Regularized regression with lasso in scikit-learn
2. Regularized classification with lasso in scikit-learn

## Part 1: Regularized regression in scikit-learn

**Goal:** Predict the violent crime rate for a community given socioeconomic and law enforcement data ([description](https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/communities.names) , [data](https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/communities.data))

### Load and prepare the crime dataset

In [1]:
# read in the dataset
import pandas as pd
url = 'https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/communities.data'
crime = pd.read_csv(url, header=None, na_values=['?'])
crime.head()

0     1        2                    3    4     5     6     7     8     9    \
0    8   NaN      NaN         Lakewoodcity    1  0.19  0.33  0.02  0.90  0.12   
1   53   NaN      NaN          Tukwilacity    1  0.00  0.16  0.12  0.74  0.45   
2   24   NaN      NaN         Aberdeentown    1  0.00  0.42  0.49  0.56  0.17   
3   34   5.0  81440.0  Willingborotownship    1  0.04  0.77  1.00  0.08  0.12   
4   42  95.0   6096.0    Bethlehemtownship    1  0.01  0.55  0.02  0.95  0.09   

   ...    118   119   120   121   122  123  124   125   126   127  
0  ...   0.12  0.26  0.20  0.06  0.04  0.9  0.5  0.32  0.14  0.20  
1  ...   0.02  0.12  0.45   NaN   NaN  NaN  NaN  0.00   NaN  0.67  
2  ...   0.01  0.21  0.02   NaN   NaN  NaN  NaN  0.00   NaN  0.43  
3  ...   0.02  0.39  0.28   NaN   NaN  NaN  NaN  0.00   NaN  0.12  
4  ...   0.04  0.09  0.02   NaN   NaN  NaN  NaN  0.00   NaN  0.03  

[5 rows x 128 columns]

In [2]:
# examine the response variable
crime[127].describe()

count    1994.000000
mean        0.237979
std         0.232985
min         0.000000
25%         0.070000
50%         0.150000
75%         0.330000
max         1.000000
Name: 127, dtype: float64

In [3]:
# remove categorical features
crime.drop([0, 1, 2, 3, 4], axis=1, inplace=True)

In [4]:
# remove rows with any missing values
crime.dropna(inplace=True)

In [5]:
# check the shape
crime.shape

(319, 123)

In [6]:
# define X and y
X = crime.drop(127, axis=1)
y = crime[127]

In [7]:
# split into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Linear regression

In [8]:
# build a linear regression model
from sklearn.linear_model import LinearRegression
linreg = LinearRegression()
linreg.fit(X_train, y_train)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/scipy/linalg/basic.py:884: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
# examine the coefficients
print (linreg.coef_)

[ -3.66188167e+00   6.98124465e-01  -2.61955467e-01  -2.85270027e-01
  -1.64740837e-01   2.46972333e-01  -1.09290051e+00  -5.96857796e-01
   1.11200239e+00  -7.21968931e-01   4.27346598e+00  -2.28040268e-01
   8.04875769e-01  -2.57934732e-01  -2.63458023e-01  -1.04616958e+00
   6.07784197e-01   7.73552561e-01   5.96468029e-02   6.90215922e-01
   2.16759430e-02  -4.87802949e-01  -5.18858404e-01   1.39478815e-01
  -1.24417942e-01   3.15003821e-01  -1.52633736e-01  -9.65003927e-01
   1.17142163e+00  -3.08546690e-02  -9.29085548e-01   1.24654586e-01
   1.98104506e-01   7.30804821e-01  -1.77337294e-01   8.32927588e-02
   3.46045601e-01   5.01837338e-01   1.57062958e+00  -4.13478807e-01
   1.39350802e+00  -3.49428114e+00   7.09577818e-01  -8.32141352e-01
  -1.39984927e+00   1.02482840e+00   2.13855006e-01  -6.18937325e-01
   5.28954490e-01   7.98294890e-02   5.93688560e-02  -1.68582667e-01
   7.31264051e-01  -1.39635208e+00   2.38507704e-01   5.50621439e-01
  -5.61447867e-01   6.18989764e-01

In [10]:
# make predictions
y_pred = linreg.predict(X_test)

In [11]:
# calculate RMSE (root mean square error)
from sklearn import metrics
import numpy as np
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

0.233813676495


### Lasso regression

**alpha:** must be positive, increase for more regularization

**normalize:** scales the features (without using StandardScaler)

In [12]:
# try alpha=0.001 and examine coefficients
from sklearn.linear_model import Lasso
lassoreg = Lasso(alpha=0.001, normalize=True)
lassoreg.fit(X_train, y_train)
print (lassoreg.coef_)

[ 0.          0.          0.00891952 -0.27423369  0.          0.          0.
 -0.         -0.          0.          0.          0.         -0.         -0.
 -0.         -0.19414627  0.          0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.          0.          0.          0.
  0.04335664 -0.          0.         -0.          0.03491474 -0.
 -0.06685424  0.          0.         -0.          0.10575313  0.          0.
  0.00890807  0.         -0.1378172  -0.30954312 -0.         -0.         -0.
 -0.          0.          0.          0.          0.         -0.          0.
  0.          0.          0.          0.          0.         -0.          0.
  0.          0.         -0.          0.         -0.         -0.          0.
  0.05257892 -0.          0.         -0.         -0.          0.          0.
  0.          0.          0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.         -0.         -0.          0.
  0.1386108

In [13]:
# try alpha=0.01 and examine coefficients
lassoreg = Lasso(alpha=0.01, normalize=True)
lassoreg.fit(X_train, y_train)
print (lassoreg.coef_)

[ 0.          0.          0.         -0.03974695  0.          0.          0.
  0.          0.         -0.          0.          0.         -0.         -0.
 -0.         -0.         -0.          0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.         -0.         -0.          0.
  0.          0.          0.         -0.          0.         -0.         -0.
  0.          0.         -0.          0.          0.          0.          0.
  0.         -0.         -0.27503063 -0.         -0.         -0.         -0.
  0.          0.          0.          0.          0.          0.          0.
  0.          0.          0.          0.         -0.          0.          0.
  0.          0.          0.          0.         -0.          0.          0.
 -0.          0.         -0.         -0.          0.          0.         -0.
  0.          0.         -0.         -0.         -0.         -0.         -0.
 -0.         -0.          0.          0.         -0.          0.          0.

In [14]:
# calculate RMSE (for alpha=0.01)
y_pred = lassoreg.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

0.198165225429


**LassoCV:** lasso regression with built-in cross-validation of the alpha parameter

**n_alphas:** number of alpha values (automatically chosen) to try

In [15]:
# select the best alpha with LassoCV
from sklearn.linear_model import LassoCV
lassoregcv = LassoCV(n_alphas=100, normalize=True, random_state=1)
lassoregcv.fit(X_train, y_train)
lassoregcv.alpha_

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/linear_model/coordinate_descent.py:466: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations
  ConvergenceWarning)


0.0015161594598125873

In [16]:
# examine the coefficients
print (lassoregcv.coef_)

[ 0.          0.          0.         -0.28113506  0.          0.          0.
  0.          0.          0.          0.          0.         -0.         -0.
 -0.         -0.15481092  0.          0.         -0.         -0.         -0.
 -0.         -0.         -0.         -0.          0.         -0.          0.
  0.06451487  0.          0.         -0.          0.         -0.
 -0.01920421  0.          0.         -0.          0.03386202  0.          0.
  0.08901243  0.         -0.08759757 -0.36986917 -0.         -0.         -0.
 -0.          0.          0.          0.          0.         -0.          0.
  0.          0.          0.          0.          0.         -0.          0.
  0.          0.         -0.          0.          0.         -0.          0.
  0.01740599 -0.          0.         -0.         -0.          0.          0.
  0.          0.          0.         -0.         -0.         -0.         -0.
 -0.         -0.         -0.          0.         -0.         -0.          0.
  0.1347103

In [17]:
# predict method uses the best alpha value
y_pred = lassoregcv.predict(X_test)
print (np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

0.160209558014


## Part 2: Regularized classification in scikit-learn

**Goal:** Predict the origin of wine using chemical analysis ([description](https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/wine.names) , [data](https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/wine.data))

### Load and prepare the wine dataset

In [18]:
# read in the dataset
url = 'https://raw.githubusercontent.com/o-m-i-d/ML_exercises_2016/master/wine.data'
wine = pd.read_csv(url, header=None)
wine.head()

0      1     2     3     4    5     6     7     8     9     10    11    12  \
0   1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64  1.04  3.92   
1   1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38  1.05  3.40   
2   1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68  1.03  3.17   
3   1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80  0.86  3.45   
4   1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32  1.04  2.93   

     13  
0  1065  
1  1050  
2  1185  
3  1480  
4   735

In [19]:
# examine the response variable
wine[0].value_counts()

2    71
1    59
3    48
Name: 0, dtype: int64

In [20]:
# define X and y
X = wine.drop(0, axis=1)
y = wine[0]

In [21]:
# split into training and testing sets
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Logistic regression (unregularized)

In [22]:
# build a logistic regression model (parameter C: inverse of regularization strength)
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(C=1e9)
logreg.fit(X_train, y_train)

LogisticRegression(C=1000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l2', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)

In [23]:
# examine the coefficients (note that here response has three classes and is not binary)
print (logreg.coef_)

[[ -3.84461620e+00   4.85935812e+00   1.38683503e+01  -2.63463001e+00
    1.00235072e-01  -4.80931725e+00   9.50217097e+00   2.68720425e+00
   -1.04590113e+01  -2.21364227e+00  -1.66416013e+00   6.72483010e+00
    6.29102796e-02]
 [  4.84763236e+00  -4.79596367e+00  -1.39611470e+01   1.41411593e+00
   -1.42449787e-02   2.75228199e+00   4.08303012e+00   2.09648245e+00
    5.39134758e+00  -6.71041740e+00   3.11083397e+00  -6.83906519e+00
   -4.34764956e-02]
 [ -9.70205899e-01   2.08269105e+00   9.41528519e-01   2.38026416e-01
   -2.49588184e-03  -9.80982809e-01  -6.54890820e+00  -4.83302283e-01
   -2.65888153e+00   2.57458082e+00  -1.30417258e+00  -2.34300445e+00
    9.48518672e-03]]


In [24]:
# generate predicted probabilities
y_pred_prob = logreg.predict_proba(X_test)
print (y_pred_prob)

[[  2.71005888e-09   9.43084268e-09   9.99999988e-01]
 [  1.03745789e-15   1.00000000e+00   4.32268574e-10]
 [  9.99999906e-01   6.22628020e-10   9.37607113e-08]
 [  3.25305895e-08   9.99999843e-01   1.24117114e-07]
 [  9.99730870e-01   1.56780051e-18   2.69129693e-04]
 [  3.07680948e-13   7.51864224e-06   9.99992481e-01]
 [  9.99778561e-01   6.51144428e-05   1.56324458e-04]
 [  9.99999720e-01   1.67144330e-20   2.80051955e-07]
 [  7.08624606e-16   3.06388638e-11   1.00000000e+00]
 [  3.81403721e-15   9.99997008e-01   2.99225936e-06]
 [  9.99967665e-01   8.35367442e-11   3.23346535e-05]
 [  9.54299689e-01   4.57000986e-02   2.11979808e-07]
 [  1.75861628e-18   1.00000000e+00   1.12563065e-10]
 [  9.99999998e-01   8.21274988e-12   1.72589098e-09]
 [  2.01653395e-08   9.99999979e-01   3.47692284e-10]
 [  4.32234177e-14   9.99999959e-01   4.13237320e-08]
 [  5.84596115e-27   4.95129598e-01   5.04870402e-01]
 [  9.99827369e-01   1.72604647e-04   2.64981140e-08]
 [  7.01283900e-13   9.99999

In [25]:
# calculate log loss (a.k.a cross-entropy loss which is a metric to assess accuracy of logistic regression)
print (metrics.log_loss(y_test, y_pred_prob))

0.3172700452


### Logistic regression (regularized)

**C:** Inverse of regularization strength, must be positive, decrease for more regularization

**penalty:** l1 (lasso)

In [26]:
# standardize X_train and X_test (transform them to have zero mean and unit variance)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
# try C=1.0 with L1 penalty
logreg = LogisticRegression(C=1.0, penalty='l1')
logreg.fit(X_train_scaled, y_train)
print (logreg.coef_)

[[ 1.26670046  0.2261138   0.54714077 -0.77343037  0.          0.
   0.75096813  0.          0.          0.          0.          1.31061501
   2.65382459]
 [-1.26468364 -0.68116415 -0.83166989  0.20150581  0.          0.
   0.42687777  0.11688239  0.20962729 -2.33686124  0.83430902  0.
  -2.60935231]
 [ 0.          0.43451283  0.3382676   0.02796131  0.          0.
  -2.65378381  0.          0.          2.14719558 -0.76086337 -0.14055937
   0.        ]]


In [28]:
# generate predicted probabilities and calculate log loss
y_pred_prob = logreg.predict_proba(X_test_scaled)
print (metrics.log_loss(y_test, y_pred_prob))

0.073990862208


**Pipeline:** chain steps together

In [29]:
# pipeline of StandardScaler and LogisticRegression
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(StandardScaler(), LogisticRegression())

**GridSearchCV:** search a grid of parameters

In [30]:
# grid search for best combination of C and penalty
from sklearn.grid_search import GridSearchCV
C_range = 10.**np.arange(-2, 3)
penalty_options = ['l1']
param_grid = dict(logisticregression__C=C_range, logisticregression__penalty=penalty_options)
grid = GridSearchCV(pipe, param_grid, cv=10, scoring='log_loss')
grid.fit(X, y)

GridSearchCV(cv=10, error_score='raise',
       estimator=Pipeline(steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('logisticregression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))]),
       fit_params={}, iid=True, n_jobs=1,
       param_grid={'logisticregression__penalty': ['l1'], 'logisticregression__C': array([  1.00000e-02,   1.00000e-01,   1.00000e+00,   1.00000e+01,
         1.00000e+02])},
       pre_dispatch='2*n_jobs', refit=True, scoring='log_loss', verbose=0)

In [31]:
# print all log loss scores
grid.grid_scores_

[mean: -1.09861, std: 0.00000, params: {'logisticregression__penalty': 'l1', 'logisticregression__C': 0.01},
 mean: -0.35492, std: 0.06894, params: {'logisticregression__penalty': 'l1', 'logisticregression__C': 0.10000000000000001},
 mean: -0.09427, std: 0.06113, params: {'logisticregression__penalty': 'l1', 'logisticregression__C': 1.0},
 mean: -0.05859, std: 0.06433, params: {'logisticregression__penalty': 'l1', 'logisticregression__C': 10.0},
 mean: -0.07091, std: 0.09296, params: {'logisticregression__penalty': 'l1', 'logisticregression__C': 100.0}]

In [32]:
# examine the best model parameters
print (grid.best_score_)
print (grid.best_params_)

-0.058588385791
{'logisticregression__penalty': 'l1', 'logisticregression__C': 10.0}
